# SPDX-FileCopyrightText: 2026 wavever
# SPDX-License-Identifier: AGPL-3.0-or-later
---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
